### ISSUE TITLE
plot.new has not been called yet

### ISSUE THREAD

**Issue by dan-piecuch-hs** [justineuro/sdRplot#1]
I get the following when I try to run this library within my R Studio (Version 1.0.153) with R version 3.3.0 (2016-05-03)

After loading the library and using the example in the code when I execute `sdRplot(5,scale,7,data)` I get the following error message

`Warning: Ignoring unknown parameters: axes, type, lab, mgp, xaxs, mar
Error in title(main = "SD Response Profiles", sub = "", cex.sub = 0.5) : 
  plot.new has not been called yet`

**Comment by justineuro** [comment]
I am not sure what you mean by "loading the library."
Try running it in the following manner in rstudio:
1. Open sdRplot.R in the rstudio editor (using the Menu: File->File open
... or through the Toolbar by clicking on the yellow folder icon).
2. Click "Run" or "Source", making sure that the current file in the editor
is sdRplot.R (tab should be highlighted).
This should source the file sdRplot.R, defining the function sdRplot(), and
run the example sdRplot(5,scale,7,data) after defining the variables used
for the example.
You may also wish to "knitr" the output by clicking on the notebook icon
(near the center of the editor toolbar).
I hope this will be of help.



On Oct 18, 2017 5:49 AM, "dan-piecuch-hs" <notifications@github.com> wrote:

I get the following when I try to run this library within my R Studio
(Version 1.0.153) with R version 3.3.0 (2016-05-03)

After loading the library and using the example in the code when I execute
sdRplot(5,scale,7,data) I get the following error message

Warning: Ignoring unknown parameters: axes, type, lab, mgp, xaxs, mar Error
in title(main = "SD Response Profiles", sub = "", cex.sub = 0.5) : plot.new
has not been called yet

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/justineuro/sdRplot/issues/1>, or mute the thread

**Comment by justineuro** [comment]
In 2., for "Run," make sure you select all of the contents of sdRplot.R
(Right-click on the region of the editor that contains the contents of the
file then Select All) before clicking on "Run."
