### ISSUE TITLE
missing group data

### ISSUE THREAD

**Issue by bem26388** [justineuro/sdRplot#2]
hi,

applying your function to more than three groups, still only three groups are displayed.  As an example, see below, the fourth group is not displayed, i.e., the plot ist just the same as calling only group 1-3.

low<-c("Serious","Slow","Useless","Tiring","Old","Hard","Long")
high<-c("Fun","Fast","Useful","Light","New","Easy","Short")
scale<-c("SA","A","N","A","SA")
grp1means<-c(4.2,4.6,4.3,4.1,4.5,4.5,4.0)
grp2means<-c(3.8,3.9,3.7,4.5,4.4,4.3,4.4)
grp3means<-c(4.5,4.7,4.4,4.2,4.6,4.4,3.9)
grp4means<-c(4.5,3.8,3.9,4.6,3.4,4.5,3.9)
data<-matrix(
    cbind(low,high,grp1means,grp2means,grp3means,grp4means),
    nrow=7,ncol=5,byrow=FALSE,
    dimnames=list(c("I1","I2","I3","I4","I5","I6","I7"),
                    c("Low","High","Grp1","Grp2","Grp3", "Grp4"))
   )
sdRplot(5,scale,7,data)

Thanks a lot,
Barb

**Comment by justineuro** [comment]
Hi Barb,
Everything is fine in your `R` code except that `ncol=6` and not `ncol=5` as you currently have in the `matrix(...)` options.  This is so since you have one additional set/group (of seven means) in your data matrix; the sample code has only three (3) sets of seven (7) group means.  The `ncol` should equal `2 + ` the number of groups (so `2 + 4 = 6` for your particular data matrix).  More precisely, that part of your code should like:
```R
data<-matrix(
  cbind(low,high,grp1means,grp2means,grp3means,grp4means),
  nrow=7,ncol=6,byrow=FALSE,
  dimnames=list(c("I1","I2","I3","I4","I5","I6","I7"),
                c("Low","High","Grp1","Grp2","Grp3", "Grp4"))
)
```
The graph that will be generated with that correction should be similar to:
![barb-n4](https://user-images.githubusercontent.com/7970053/96964743-91e7ad80-153d-11eb-89af-c82e2d1a8057.png)


Hoping this will help.
Best,
Justine Leon

**Comment by bem26388** [comment]
Hi,

yes, thank you so much! It worked out perfectly!! Looks all great!

Best,
Barb
